// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xconf.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateNamespaceRequest struct {
	Space                *Namespace `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateNamespaceRequest) Reset()         { *m = CreateNamespaceRequest{} }
func (m *CreateNamespaceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNamespaceRequest) ProtoMessage()    {}
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd395bcdc4a182b, []int{0}
}

func (m *CreateNamespaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespaceRequest.Unmarshal(m, b)
}
func (m *CreateNamespaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespaceRequest.Marshal(b, m, deterministic)
}
func (m *CreateNamespaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespaceRequest.Merge(m, src)
}
func (m *CreateNamespaceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNamespaceRequest.Size(m)
}
func (m *CreateNamespaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespaceRequest proto.InternalMessageInfo

func (m *CreateNamespaceRequest) GetSpace() *Namespace {
	if m != nil {
		return m.Space
	}
	return nil
}

type ListNamespacesResponse struct {
	Spaces               []*Namespace `protobuf:"bytes,1,rep,name=spaces,proto3" json:"spaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListNamespacesResponse) Reset()         { *m = ListNamespacesResponse{} }
func (m *ListNamespacesResponse) String() string { return proto.CompactTextString(m) }
func (*ListNamespacesResponse) ProtoMessage()    {}
func (*ListNamespacesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd395bcdc4a182b, []int{1}
}

func (m *ListNamespacesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNamespacesResponse.Unmarshal(m, b)
}
func (m *ListNamespacesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNamespacesResponse.Marshal(b, m, deterministic)
}
func (m *ListNamespacesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNamespacesResponse.Merge(m, src)
}
func (m *ListNamespacesResponse) XXX_Size() int {
	return xxx_messageInfo_ListNamespacesResponse.Size(m)
}
func (m *ListNamespacesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNamespacesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNamespacesResponse proto.InternalMessageInfo

func (m *ListNamespacesResponse) GetSpaces() []*Namespace {
	if m != nil {
		return m.Spaces
	}
	return nil
}

type CreateGroupRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group                *Group   `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd395bcdc4a182b, []int{2}
}

func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (m *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(m, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

func (m *CreateGroupRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateGroupRequest) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

type ListGroupsRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsRequest) Reset()         { *m = ListGroupsRequest{} }
func (m *ListGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroupsRequest) ProtoMessage()    {}
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd395bcdc4a182b, []int{3}
}

func (m *ListGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsRequest.Unmarshal(m, b)
}
func (m *ListGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsRequest.Marshal(b, m, deterministic)
}
func (m *ListGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsRequest.Merge(m, src)
}
func (m *ListGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroupsRequest.Size(m)
}
func (m *ListGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsRequest proto.InternalMessageInfo

func (m *ListGroupsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type ListGroupsResponse struct {
	Groups               []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsResponse) Reset()         { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()    {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd395bcdc4a182b, []int{4}
}

func (m *ListGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsResponse.Unmarshal(m, b)
}
func (m *ListGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsResponse.Marshal(b, m, deterministic)
}
func (m *ListGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsResponse.Merge(m, src)
}
func (m *ListGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupsResponse.Size(m)
}
func (m *ListGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsResponse proto.InternalMessageInfo

func (m *ListGroupsResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type GetConfigRequest struct {
	// namespace/group
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd395bcdc4a182b, []int{5}
}

func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(m, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *GetConfigRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateConfigRequest struct {
	// namespace/group
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Config               *Config  `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConfigRequest) Reset()         { *m = CreateConfigRequest{} }
func (m *CreateConfigRequest) String() string { return proto.CompactTextString(m) }
func (*CreateConfigRequest) ProtoMessage()    {}
func (*CreateConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd395bcdc4a182b, []int{6}
}

func (m *CreateConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConfigRequest.Unmarshal(m, b)
}
func (m *CreateConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConfigRequest.Marshal(b, m, deterministic)
}
func (m *CreateConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConfigRequest.Merge(m, src)
}
func (m *CreateConfigRequest) XXX_Size() int {
	return xxx_messageInfo_CreateConfigRequest.Size(m)
}
func (m *CreateConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConfigRequest proto.InternalMessageInfo

func (m *CreateConfigRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateConfigRequest) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type UpdateConfigRequest struct {
	// namespace/group
	Parent               string                `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Config               *Config               `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateConfigRequest) Reset()         { *m = UpdateConfigRequest{} }
func (m *UpdateConfigRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigRequest) ProtoMessage()    {}
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd395bcdc4a182b, []int{7}
}

func (m *UpdateConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigRequest.Unmarshal(m, b)
}
func (m *UpdateConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigRequest.Marshal(b, m, deterministic)
}
func (m *UpdateConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigRequest.Merge(m, src)
}
func (m *UpdateConfigRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigRequest.Size(m)
}
func (m *UpdateConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigRequest proto.InternalMessageInfo

func (m *UpdateConfigRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *UpdateConfigRequest) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *UpdateConfigRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteConfigRequest struct {
	// namespace/group/id
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteConfigRequest) Reset()         { *m = DeleteConfigRequest{} }
func (m *DeleteConfigRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteConfigRequest) ProtoMessage()    {}
func (*DeleteConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd395bcdc4a182b, []int{8}
}

func (m *DeleteConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteConfigRequest.Unmarshal(m, b)
}
func (m *DeleteConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteConfigRequest.Marshal(b, m, deterministic)
}
func (m *DeleteConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteConfigRequest.Merge(m, src)
}
func (m *DeleteConfigRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteConfigRequest.Size(m)
}
func (m *DeleteConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteConfigRequest proto.InternalMessageInfo

func (m *DeleteConfigRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *DeleteConfigRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListConfigsRequest struct {
	// namespace/group
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListConfigsRequest) Reset()         { *m = ListConfigsRequest{} }
func (m *ListConfigsRequest) String() string { return proto.CompactTextString(m) }
func (*ListConfigsRequest) ProtoMessage()    {}
func (*ListConfigsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd395bcdc4a182b, []int{9}
}

func (m *ListConfigsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListConfigsRequest.Unmarshal(m, b)
}
func (m *ListConfigsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListConfigsRequest.Marshal(b, m, deterministic)
}
func (m *ListConfigsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListConfigsRequest.Merge(m, src)
}
func (m *ListConfigsRequest) XXX_Size() int {
	return xxx_messageInfo_ListConfigsRequest.Size(m)
}
func (m *ListConfigsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListConfigsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListConfigsRequest proto.InternalMessageInfo

func (m *ListConfigsRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

type ListConfigsResponse struct {
	Configs              []*Config `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListConfigsResponse) Reset()         { *m = ListConfigsResponse{} }
func (m *ListConfigsResponse) String() string { return proto.CompactTextString(m) }
func (*ListConfigsResponse) ProtoMessage()    {}
func (*ListConfigsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd395bcdc4a182b, []int{10}
}

func (m *ListConfigsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListConfigsResponse.Unmarshal(m, b)
}
func (m *ListConfigsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListConfigsResponse.Marshal(b, m, deterministic)
}
func (m *ListConfigsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListConfigsResponse.Merge(m, src)
}
func (m *ListConfigsResponse) XXX_Size() int {
	return xxx_messageInfo_ListConfigsResponse.Size(m)
}
func (m *ListConfigsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListConfigsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListConfigsResponse proto.InternalMessageInfo

func (m *ListConfigsResponse) GetConfigs() []*Config {
	if m != nil {
		return m.Configs
	}
	return nil
}

type ConfigMeta struct {
	Version              string               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Comment              string               `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Canary               string               `protobuf:"bytes,3,opt,name=canary,proto3" json:"canary,omitempty"`
	Ctime                *timestamp.Timestamp `protobuf:"bytes,4,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Mtime                *timestamp.Timestamp `protobuf:"bytes,5,opt,name=mtime,proto3" json:"mtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ConfigMeta) Reset()         { *m = ConfigMeta{} }
func (m *ConfigMeta) String() string { return proto.CompactTextString(m) }
func (*ConfigMeta) ProtoMessage()    {}
func (*ConfigMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd395bcdc4a182b, []int{11}
}

func (m *ConfigMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigMeta.Unmarshal(m, b)
}
func (m *ConfigMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigMeta.Marshal(b, m, deterministic)
}
func (m *ConfigMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigMeta.Merge(m, src)
}
func (m *ConfigMeta) XXX_Size() int {
	return xxx_messageInfo_ConfigMeta.Size(m)
}
func (m *ConfigMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigMeta proto.InternalMessageInfo

func (m *ConfigMeta) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ConfigMeta) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *ConfigMeta) GetCanary() string {
	if m != nil {
		return m.Canary
	}
	return ""
}

func (m *ConfigMeta) GetCtime() *timestamp.Timestamp {
	if m != nil {
		return m.Ctime
	}
	return nil
}

func (m *ConfigMeta) GetMtime() *timestamp.Timestamp {
	if m != nil {
		return m.Mtime
	}
	return nil
}

type Config struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string      `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Meta                 *ConfigMeta `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd395bcdc4a182b, []int{12}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Config) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Config) GetMeta() *ConfigMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Group struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd395bcdc4a182b, []int{13}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Namespace struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}
func (*Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fd395bcdc4a182b, []int{14}
}

func (m *Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespace.Unmarshal(m, b)
}
func (m *Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespace.Marshal(b, m, deterministic)
}
func (m *Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespace.Merge(m, src)
}
func (m *Namespace) XXX_Size() int {
	return xxx_messageInfo_Namespace.Size(m)
}
func (m *Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_Namespace proto.InternalMessageInfo

func (m *Namespace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateNamespaceRequest)(nil), "api.CreateNamespaceRequest")
	proto.RegisterType((*ListNamespacesResponse)(nil), "api.ListNamespacesResponse")
	proto.RegisterType((*CreateGroupRequest)(nil), "api.CreateGroupRequest")
	proto.RegisterType((*ListGroupsRequest)(nil), "api.ListGroupsRequest")
	proto.RegisterType((*ListGroupsResponse)(nil), "api.ListGroupsResponse")
	proto.RegisterType((*GetConfigRequest)(nil), "api.GetConfigRequest")
	proto.RegisterType((*CreateConfigRequest)(nil), "api.CreateConfigRequest")
	proto.RegisterType((*UpdateConfigRequest)(nil), "api.UpdateConfigRequest")
	proto.RegisterType((*DeleteConfigRequest)(nil), "api.DeleteConfigRequest")
	proto.RegisterType((*ListConfigsRequest)(nil), "api.ListConfigsRequest")
	proto.RegisterType((*ListConfigsResponse)(nil), "api.ListConfigsResponse")
	proto.RegisterType((*ConfigMeta)(nil), "api.ConfigMeta")
	proto.RegisterType((*Config)(nil), "api.Config")
	proto.RegisterType((*Group)(nil), "api.Group")
	proto.RegisterType((*Namespace)(nil), "api.Namespace")
}

func init() { proto.RegisterFile("xconf.proto", fileDescriptor_1fd395bcdc4a182b) }

var fileDescriptor_1fd395bcdc4a182b = []byte{
	// 680 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5f, 0x4f, 0x13, 0x41,
	0x10, 0xa7, 0xd0, 0x2b, 0xe9, 0x94, 0x80, 0x4e, 0x63, 0xb9, 0x1c, 0x24, 0x34, 0x8b, 0x1a, 0x1f,
	0xcc, 0x21, 0x68, 0xa2, 0x11, 0xff, 0x10, 0x50, 0x79, 0x11, 0x1f, 0x2e, 0x18, 0x8d, 0x2f, 0x66,
	0xb9, 0x6e, 0x9b, 0x0b, 0xdc, 0xed, 0xd9, 0xdd, 0x1a, 0xf9, 0x14, 0x7e, 0x1b, 0x9f, 0xfc, 0x70,
	0x66, 0xff, 0xb5, 0x7b, 0x47, 0x09, 0x3c, 0xf8, 0x76, 0x3b, 0x33, 0xbf, 0x99, 0xdf, 0xcc, 0xee,
	0x6f, 0x0e, 0x3a, 0xbf, 0x52, 0x5e, 0x0c, 0xe3, 0x72, 0xcc, 0x25, 0xc7, 0x25, 0x5a, 0x66, 0x51,
	0x7f, 0xc4, 0xf9, 0xe8, 0x82, 0xed, 0x68, 0xd3, 0xd9, 0x64, 0xb8, 0x33, 0xcc, 0xd8, 0xc5, 0xe0,
	0x7b, 0x4e, 0xc5, 0xb9, 0x09, 0x8b, 0x36, 0xea, 0x11, 0x2c, 0x2f, 0xe5, 0xa5, 0x75, 0x6e, 0xd5,
	0x9d, 0x32, 0xcb, 0x99, 0x90, 0x34, 0x2f, 0x4d, 0x00, 0x79, 0x03, 0xbd, 0xa3, 0x31, 0xa3, 0x92,
	0x7d, 0xa2, 0x39, 0x13, 0x25, 0x4d, 0x59, 0xc2, 0x7e, 0x4c, 0x98, 0x90, 0x78, 0x1f, 0x02, 0x7d,
	0x0e, 0x1b, 0xfd, 0xc6, 0xa3, 0xce, 0xde, 0x6a, 0x4c, 0xcb, 0x2c, 0x9e, 0x45, 0x19, 0x27, 0x39,
	0x80, 0xde, 0xc7, 0x4c, 0xc8, 0xa9, 0x5d, 0x24, 0x4c, 0x94, 0xbc, 0x10, 0x0c, 0x1f, 0x42, 0xcb,
	0x58, 0xc2, 0x46, 0x7f, 0x69, 0x4e, 0x02, 0xeb, 0x25, 0xa7, 0x80, 0x86, 0xc1, 0xf1, 0x98, 0x4f,
	0x4a, 0x57, 0x7d, 0x13, 0xda, 0x85, 0x0b, 0xd5, 0x0c, 0xda, 0xc9, 0xcc, 0x80, 0x7d, 0x08, 0x46,
	0x2a, 0x3a, 0x5c, 0xd4, 0xdc, 0x40, 0xa7, 0x36, 0x78, 0xe3, 0x20, 0xbb, 0x70, 0x57, 0xf1, 0xd2,
	0x36, 0x71, 0xab, 0xa4, 0xe4, 0x05, 0xa0, 0x0f, 0xb1, 0x6d, 0x10, 0x68, 0xe9, 0x8c, 0xae, 0x0d,
	0xbf, 0x96, 0xf5, 0x90, 0x97, 0x70, 0xe7, 0x98, 0xc9, 0x23, 0x5e, 0x0c, 0xb3, 0x91, 0xab, 0xd5,
	0x83, 0x56, 0x49, 0xc7, 0xac, 0x90, 0xb6, 0x90, 0x3d, 0xe1, 0x2a, 0x2c, 0x66, 0x03, 0xcd, 0xbb,
	0x9d, 0x2c, 0x66, 0x03, 0x92, 0x40, 0xd7, 0xb4, 0x7f, 0x3b, 0xf8, 0x36, 0xb4, 0x52, 0x1d, 0x68,
	0x5b, 0xef, 0x68, 0x3a, 0x16, 0x6b, 0x5d, 0xe4, 0x77, 0x03, 0xba, 0x9f, 0xcb, 0xc1, 0x7f, 0x4d,
	0x8a, 0xfb, 0xd0, 0x99, 0xe8, 0x9c, 0xfa, 0xf1, 0x85, 0x4b, 0x3a, 0x32, 0x8a, 0xcd, 0x03, 0x8b,
	0xdd, 0x03, 0x8b, 0x3f, 0xa8, 0xf7, 0x79, 0x42, 0xc5, 0x79, 0x02, 0x26, 0x5c, 0x7d, 0x93, 0xd7,
	0xd0, 0x7d, 0xc7, 0x2e, 0xd8, 0x6d, 0x09, 0xd5, 0x87, 0xf4, 0xd8, 0x5c, 0x8d, 0x01, 0x8b, 0x1b,
	0xd0, 0xe4, 0x15, 0x74, 0x2b, 0xd1, 0xf6, 0x26, 0x1f, 0xc0, 0xb2, 0x69, 0xc5, 0x5d, 0x65, 0xa5,
	0x4d, 0xe7, 0x23, 0x7f, 0x1b, 0x00, 0xc6, 0x76, 0xc2, 0x24, 0xc5, 0x10, 0x96, 0x7f, 0xb2, 0xb1,
	0xc8, 0x78, 0x61, 0xab, 0xb8, 0xa3, 0xf2, 0xa4, 0x3c, 0xcf, 0x55, 0x7d, 0xc3, 0xd4, 0x1d, 0x15,
	0xb1, 0x94, 0x16, 0x74, 0x7c, 0xa9, 0xa7, 0xd4, 0x4e, 0xec, 0x09, 0x9f, 0x40, 0x90, 0x2a, 0x01,
	0x86, 0xcd, 0x6b, 0x86, 0x77, 0xea, 0xd4, 0x99, 0x98, 0x40, 0x85, 0xc8, 0x35, 0x22, 0xb8, 0x19,
	0xa1, 0x03, 0xc9, 0x17, 0x68, 0x19, 0xf6, 0x76, 0x88, 0x0d, 0x37, 0x44, 0xc3, 0xb7, 0x90, 0x15,
	0xbe, 0xfa, 0x88, 0xdb, 0xd0, 0xcc, 0x99, 0xa4, 0xf6, 0x4e, 0xd7, 0xbc, 0xb1, 0xa8, 0x11, 0x24,
	0xda, 0x49, 0x36, 0x20, 0xd0, 0xaf, 0x1e, 0x11, 0x9a, 0x4a, 0x34, 0x36, 0xb3, 0xfe, 0x26, 0x5b,
	0xd0, 0x9e, 0x2a, 0x7b, 0x5e, 0xc0, 0xde, 0x9f, 0x26, 0x04, 0x5f, 0xd5, 0x88, 0xf1, 0x00, 0xd6,
	0x6a, 0x1b, 0x07, 0x37, 0x4c, 0xc5, 0xb9, 0x7b, 0x28, 0xaa, 0xed, 0x0d, 0xb2, 0x80, 0xc7, 0xb0,
	0x5a, 0xdd, 0x39, 0xd8, 0xbb, 0x32, 0x97, 0xf7, 0x6a, 0x09, 0x46, 0x26, 0xf1, 0xfc, 0x05, 0x45,
	0x16, 0xf0, 0x19, 0x74, 0xbc, 0xd5, 0x83, 0xeb, 0x1e, 0x0d, 0x7f, 0x19, 0x45, 0x9e, 0xe6, 0xc9,
	0x02, 0xbe, 0x05, 0x98, 0xed, 0x09, 0xec, 0x4d, 0x4b, 0x54, 0x76, 0x4d, 0xb4, 0x7e, 0xc5, 0x3e,
	0x2d, 0xfb, 0x1c, 0x56, 0x7c, 0xc9, 0x63, 0xe8, 0xd5, 0xad, 0xe8, 0x23, 0xf2, 0x5f, 0xa8, 0x01,
	0xfa, 0xb2, 0xb6, 0xc0, 0x39, 0x4a, 0xaf, 0x03, 0x77, 0xa1, 0x3d, 0x5d, 0x50, 0x78, 0xcf, 0x74,
	0x53, 0x5b, 0x58, 0x75, 0xc8, 0x21, 0xac, 0xf8, 0x8a, 0xb5, 0xb5, 0xe6, 0x88, 0x38, 0xba, 0x66,
	0xf8, 0x3a, 0x47, 0xc7, 0x13, 0x22, 0xce, 0x46, 0x52, 0x15, 0x72, 0x14, 0x5e, 0x75, 0xb8, 0x61,
	0x1d, 0x6e, 0x42, 0x37, 0xe5, 0x79, 0xcc, 0x0b, 0x36, 0xe2, 0xb1, 0xf9, 0x3d, 0xd2, 0x32, 0xfb,
	0x16, 0xc4, 0xfb, 0xb4, 0xcc, 0xce, 0x5a, 0xba, 0xe6, 0xd3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xfe, 0x37, 0xf2, 0x7b, 0x39, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// XconfClient is the client API for Xconf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type XconfClient interface {
	CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*Namespace, error)
	ListNamespaces(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListNamespacesResponse, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*Group, error)
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	CreateConfig(ctx context.Context, in *CreateConfigRequest, opts ...grpc.CallOption) (*Config, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*Config, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*Config, error)
	DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...grpc.CallOption) (*ListConfigsResponse, error)
}

type xconfClient struct {
	cc *grpc.ClientConn
}

func NewXconfClient(cc *grpc.ClientConn) XconfClient {
	return &xconfClient{cc}
}

func (c *xconfClient) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*Namespace, error) {
	out := new(Namespace)
	err := c.cc.Invoke(ctx, "/api.Xconf/CreateNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xconfClient) ListNamespaces(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListNamespacesResponse, error) {
	out := new(ListNamespacesResponse)
	err := c.cc.Invoke(ctx, "/api.Xconf/ListNamespaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xconfClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*Group, error) {
	out := new(Group)
	err := c.cc.Invoke(ctx, "/api.Xconf/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xconfClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, "/api.Xconf/ListGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xconfClient) CreateConfig(ctx context.Context, in *CreateConfigRequest, opts ...grpc.CallOption) (*Config, error) {
	out := new(Config)
	err := c.cc.Invoke(ctx, "/api.Xconf/CreateConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xconfClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*Config, error) {
	out := new(Config)
	err := c.cc.Invoke(ctx, "/api.Xconf/UpdateConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xconfClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*Config, error) {
	out := new(Config)
	err := c.cc.Invoke(ctx, "/api.Xconf/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xconfClient) DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.Xconf/DeleteConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xconfClient) ListConfigs(ctx context.Context, in *ListConfigsRequest, opts ...grpc.CallOption) (*ListConfigsResponse, error) {
	out := new(ListConfigsResponse)
	err := c.cc.Invoke(ctx, "/api.Xconf/ListConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XconfServer is the server API for Xconf service.
type XconfServer interface {
	CreateNamespace(context.Context, *CreateNamespaceRequest) (*Namespace, error)
	ListNamespaces(context.Context, *empty.Empty) (*ListNamespacesResponse, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*Group, error)
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	CreateConfig(context.Context, *CreateConfigRequest) (*Config, error)
	UpdateConfig(context.Context, *UpdateConfigRequest) (*Config, error)
	GetConfig(context.Context, *GetConfigRequest) (*Config, error)
	DeleteConfig(context.Context, *DeleteConfigRequest) (*empty.Empty, error)
	ListConfigs(context.Context, *ListConfigsRequest) (*ListConfigsResponse, error)
}

// UnimplementedXconfServer can be embedded to have forward compatible implementations.
type UnimplementedXconfServer struct {
}

func (*UnimplementedXconfServer) CreateNamespace(ctx context.Context, req *CreateNamespaceRequest) (*Namespace, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNamespace not implemented")
}
func (*UnimplementedXconfServer) ListNamespaces(ctx context.Context, req *empty.Empty) (*ListNamespacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNamespaces not implemented")
}
func (*UnimplementedXconfServer) CreateGroup(ctx context.Context, req *CreateGroupRequest) (*Group, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (*UnimplementedXconfServer) ListGroups(ctx context.Context, req *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroups not implemented")
}
func (*UnimplementedXconfServer) CreateConfig(ctx context.Context, req *CreateConfigRequest) (*Config, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConfig not implemented")
}
func (*UnimplementedXconfServer) UpdateConfig(ctx context.Context, req *UpdateConfigRequest) (*Config, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (*UnimplementedXconfServer) GetConfig(ctx context.Context, req *GetConfigRequest) (*Config, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (*UnimplementedXconfServer) DeleteConfig(ctx context.Context, req *DeleteConfigRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConfig not implemented")
}
func (*UnimplementedXconfServer) ListConfigs(ctx context.Context, req *ListConfigsRequest) (*ListConfigsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConfigs not implemented")
}

func RegisterXconfServer(s *grpc.Server, srv XconfServer) {
	s.RegisterService(&_Xconf_serviceDesc, srv)
}

func _Xconf_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XconfServer).CreateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Xconf/CreateNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XconfServer).CreateNamespace(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xconf_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XconfServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Xconf/ListNamespaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XconfServer).ListNamespaces(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xconf_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XconfServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Xconf/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XconfServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xconf_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XconfServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Xconf/ListGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XconfServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xconf_CreateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XconfServer).CreateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Xconf/CreateConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XconfServer).CreateConfig(ctx, req.(*CreateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xconf_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XconfServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Xconf/UpdateConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XconfServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xconf_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XconfServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Xconf/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XconfServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xconf_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XconfServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Xconf/DeleteConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XconfServer).DeleteConfig(ctx, req.(*DeleteConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xconf_ListConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XconfServer).ListConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Xconf/ListConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XconfServer).ListConfigs(ctx, req.(*ListConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Xconf_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Xconf",
	HandlerType: (*XconfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNamespace",
			Handler:    _Xconf_CreateNamespace_Handler,
		},
		{
			MethodName: "ListNamespaces",
			Handler:    _Xconf_ListNamespaces_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _Xconf_CreateGroup_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _Xconf_ListGroups_Handler,
		},
		{
			MethodName: "CreateConfig",
			Handler:    _Xconf_CreateConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _Xconf_UpdateConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _Xconf_GetConfig_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _Xconf_DeleteConfig_Handler,
		},
		{
			MethodName: "ListConfigs",
			Handler:    _Xconf_ListConfigs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xconf.proto",
}
